### ISSUE TITLE
"Streams and IBM Cloud Pak for Data" points to https://ibmstreams.github.io/

### ISSUE THREAD

**Issue by markheger** [IBMStreams/IBMStreams.github.io#36]
What shall be the correct link?

**Comment by markheger** [comment]
@natashadsilva shall the link be changed to 
https://www.ibm.com/support/knowledgecenter/SSQNUZ

or

https://www.ibm.com/support/knowledgecenter/en/SSQNUZ_3.0.1/cpd/svc/streams/developing-intro.html
?

**Comment by natashadsilva** [comment]
That link was originally supposed to go to https://developer.ibm.com/streamsdev/2019/02/28/ibm-streams-comes-to-the-private-cloud/ which is the announcement of the CPD release.  But that post will be archived when Streamsdev is shut down. 

Better is to link to the getting started page in CPD community:
https://community.ibm.com/community/user/cloudpakfordata/blogs/natasha-dsilva1/2020/04/22/get-started-with-streaming-analytics

**Comment by markheger** [comment]
Is there a more final link available without "**blogs/natasha-dsilva1/2020/04/22**/" ?

for example:
https://community.ibm.com/community/user/cloudpakfordata/viewdocument/get-started-with-streaming-analytics
