### ISSUE TITLE
change "Streaming Analytics" to something like "Available on the cloud"?

### ISSUE THREAD

**Issue by hildrum** [IBMStreams/IBMStreams.github.io#8]
I think the title could be improved here:
<img width="207" alt="screen shot 2015-08-03 at 11 04 54 am" src="https://cloud.githubusercontent.com/assets/5419652/9040373/b5f9ddfa-39cf-11e5-8fee-272fe477a2d2.png">

The main point of that what's new item is that it can now be used on the cloud, and the title should reflect that.   Possible alternatives:
- Cloud-ready
- Available on Cloud
- On Bluemix
- On Bluemix as Streaming Analytics
- Now on Bluemix, IBM's cloud service
- Available on Bluemix as Streaming Analytics
- Available on the Cloud as Streaming Analytics

**Comment by chanskw** [comment]
Rejecting this issue.  The Streaming Analytics name is the official name on the service.
The Cloud icon reflects that this is on the cloud.  In the description, we do mention that this is for Bluemix.  So I think we have enough clues that this is on the cloud.
